name: Diffusers
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10.14
  - pip
  - pytorch=2.3.1
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - diffusers
  - accelerate
  - transformers
  - xformers
